name: 'Get Issue Labels Action'
description: 'Get issue labels in realtime'
inputs:
  number:
    description: 'Issue number'
    required: true
  label:
    description: 'Label title'
    required: true
runs:
  using: "composite"
  steps:
    - name: Add issue label
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        GH_REPO: ${{ github.repository }}
      run: |
        echo repository: ${{ github.repository }}
        echo issue: ${{ inputs.number }}
        echo label: ${{ inputs.label }}
        gh issue edit "${{ inputs.number }}" --add-label "${{ inputs.label }}"
